### ISSUE TITLE
More info in circular references diagnostics

### ISSUE THREAD

**Issue by jberdine** [cristianoc/reanalyze#16]
On some code I see many `Results for ... could be inaccurate because of circular references` warnings. More information on what the cycle of references is would make these possibly debuggable.

**Comment by cristianoc** [comment]
And that's an old message too, coming from a time when there was not a complete fixpoint computed. In reality there's no inaccuracy left.

The one thing left is: if the sources are coming from a pre-processor, which sprinkled with things like
```ml
#1 "eol_detect.ml"
```
then the location info is going to be inaccurate, and might lead to cycles only for that reason.

**Comment by jberdine** [comment]
Hmm, ok, don't worry about this for now then, I'll hunt some more.

**Comment by jberdine** [comment]
> Btw Q: is there a way to ignore those directives, perhaps as a project compilation setting? That would take care of the issues.

Well, ocamlformat silently removes them, so for ocaml code there is that. :-)

There must be a reasonably simple pre-processor that would remove them though.

**Comment by cristianoc** [comment]
Turned off the warning, as it's of little value. Mostly just noise and confusing.
https://github.com/cristianoc/reanalyze/commit/1aa7f468cdbc90df7882d50fe91cfce6527f525e
