### ISSUE TITLE
Whitelist for interface files constituting a library interface

### ISSUE THREAD

**Issue by jberdine** [cristianoc/reanalyze#18]
In the implementation of a library, it is usual for much of it to be dead, as there is no client that actually calls the entry points. In order to analyze libraries, it would be good to be able to specify an interface file (or maybe several) that constitutes the exposed library api. Everything in that file ought to then be interpreted as `@live`.

**Comment by cristianoc** [comment]
Can this done with the current `Whitelist=???` mechanism, which operates at the level of file paths?

**Comment by cristianoc** [comment]
That mechanism should also be moved out of env variable and into command-line space.

**Comment by cristianoc** [comment]
Wrong one closed automatically.

**Comment by jberdine** [comment]
Maybe I'm confused, but I interpreted `Whitelist` as suppressing reports on a particular path, rather than marking everything in it as live. That is, all the code that is not in the exposed api but only reachable through it should also be considered live.

**Comment by jberdine** [comment]
I have tried `Whitelist=path/to/api.mli reanalyze ...` and got
```
  Warning Dead Value
  File "path/to/api.mli", ...
```
User error?

**Comment by cristianoc** [comment]
I think we just demonstrated that the mechanism is not intuitive and I’ve probably forgotten how it works.

So -live-path it is.

**Comment by cristianoc** [comment]
Done here: https://github.com/cristianoc/reanalyze/pull/23

**Comment by jberdine** [comment]
Looks good, thanks!
