### ISSUE TITLE
Report incorrect annotations

### ISSUE THREAD

**Issue by jberdine** [cristianoc/reanalyze#24]
If I add a `[@dead]` annotation to the declaration of a function `f` in an interface file, when `f` is actually live, then there is a report that the implementation is dead (assuming all the uses are from other modules). It would be more useful if such incorrect annotations were reported as such, rather than trusting them and misreporting on the implementation. I'm thinking of the use case of using the dead annotations as a way to record the current state of the dead code analysis, and thinking of what happens when a new use of a previously dead value is added. In that case, the old dead annotation is incorrect, and it would be helpful to report that.

**Comment by cristianoc** [comment]
I think it makes sense,
Curious: do you have an example where this happened?

**Comment by cristianoc** [comment]
There's actually one issue.
If you develop with a dead code PPX, as I'm doing in the sample projects. Then as soon as a `@dead` annotation is found, that code is gone, as if it had never been written.
So there's no opportunity to report a wrong annotation.

So I'm not sure so far.

**Comment by jberdine** [comment]
Not having used the dead code analyzer for very long, this scenario is still hypothetical. But I'm working with a code base that I'm not yet familiar with, and there are several alternative implementations where one is dead at any given time. I don't want to remove the alternative implementations, but it would be good to know what code across the project is dead in the current configuration, to better understand refactoring constraints, etc.

**Comment by cristianoc** [comment]
Whatever you find out, curious to learn more from experience.
You should get the warning now.
