### ISSUE TITLE
Add a watch mode?

### ISSUE THREAD

**Issue by johnhaley81** [cristianoc/reanalyze#27]
Thanks for this awesome tool!

While going through a repo and resolving things that are brough up, it would be nice to get a stream of remaining dead code left.

**Comment by cristianoc** [comment]
@johnhaley81 is that for bucklescript/JS or dune/native?

**Comment by cristianoc** [comment]
It will probably be possible to integrate with bsb in future. Though it will take some time.
No plan to have a dedicated watch mode.

**Comment by johnhaley81** [comment]
I'm currently using it with Bucklescript

**Comment by cristianoc** [comment]
@johnhaley81 if you run the bs watcher, all you need is to call reanalyze from time to time.

Later on, special support will be added to bsb, but it takes a little time to get there.

How does that sound?

**Comment by johnhaley81** [comment]
That's what I'm doing right now and it is definitely manageable. The special support sounds great whenever that's able to be built. Certainly no rush 😊

**Comment by cristianoc** [comment]
Great!
