### ISSUE TITLE
Track unused record fields?

### ISSUE THREAD

**Issue by zth** [cristianoc/reanalyze#30]
Would it be possible to somehow track unused fields on records?

The reason I ask is because both `reason-relay` and `graphql_ppx` (v1.0 of `graphql_ppx` which is just around the corner) output records to describe the data coming back from the GraphQL API through fragments/queries/subscriptions. If we can use Reanalyze to (opt in?) track whether you _actually use_ what you select in your GraphQL operations (through access of the record fields), that'd be a really big win, because it'd mean we can help the user to not fetch more data than what's needed.

This has been attempted via `eslint` plugins before, but the result has never really been that solid to my knowledge. Maybe we have a better chance of doing this well in ReasonML with Reanalyze?

I understand there's nuances to this, but I figured we could get a discussion going.

cc @jfrolich who I'm sure would be interested in this too, and @sgrove who I know have expressed interest for similar features previously.

**Comment by cristianoc** [comment]
@zth this is there today, but there are several interpretations of unused field.
In the implementation, unused means you never do `r.x` for record `r`.

Give it a try, and sew how that matches the patterns you're looking to eliminate.

**Comment by zth** [comment]
🤯 I'll re open this if I find anything while experimenting, sorry for not looking up things better before opening the issue!

**Comment by jfrolich** [comment]
Yes this would be so great! With `graphql-ppx` the complexity is that the types are generated by the ppx and reanalyze is running before the ppx'es I think (and obviously the `@dead` annotations cannot be added to code that is generated in a `ppx`). It would actually be really interesting to see if reanalyze could add a `@dead` directive to operations/fragments in the GraphQL code 🤯.
