### ISSUE TITLE
Add check for dead modules.

### ISSUE THREAD

**Issue by jberdine** [cristianoc/reanalyze#33]
When a module defined by a ml-mli pair of files is dead, it would be nice to report that concisely rather than to report that each item in the module is dead.

**Comment by cristianoc** [comment]
Indeed dead module is not something checked for currently, and it would be nice to have in future. In particular when a module becomes dead by having all its elements dead, perhaps, transitively, so it's not immediately obvious before running the analysis.

**Comment by cristianoc** [comment]
@jberdine we're getting there: https://github.com/cristianoc/reanalyze/pull/61.

**Comment by cristianoc** [comment]
Done. Under `-experimental`.
