### ISSUE TITLE
Symbolic links to _esy disturb build.

### ISSUE THREAD

**Issue by cristianoc** [cristianoc/reanalyze#44]

**Comment by cristianoc** [comment]
E.g.
```
ls -l examples/DeadCodePPX.exe
lrwxr-xr-x  1 cristianoc  1876110778  57 May  4 07:59 examples/DeadCodePPX.exe -> ../_esy/default/build/install/default/bin/DeadCodePPX.exe
```

**Comment by imbsky** [comment]
These changes should work around it, but this is a really dirty workaround and I think there is a better workaround.
https://github.com/imbsky/reanalyze/tree/avoid-dune-error

**Comment by imbsky** [comment]
By the way, changing the public name is not required, but if you installed reanalyze with opam, you will have to type `reanalyze.exe` at the command line.

**Comment by cristianoc** [comment]
PR is here: https://github.com/cristianoc/reanalyze/pulls

**Comment by cristianoc** [comment]
Relevant: https://github.com/cristianoc/reanalyze/pull/48
