### ISSUE TITLE
Dead code warnings on ppx generated code

### ISSUE THREAD

**Issue by jberdine** [cristianoc/reanalyze#6]
The measures that ppx code generators take to avoid the compiler's various "unused" warnings do not work for reanalyze, and result in dead code warnings on generated code. For instance:
```ocaml
let compare_int = compare

type t = int [@@deriving_inline compare]

let _ = fun (_ : t) -> ()
let compare = (compare_int : t -> t -> int)
let _ = compare

[@@@end]
```
leads to
```
  Warning Dead Value
  dce_test.ml 5:1-25
  _ has no side effects and can be removed
  <-- line 5
  let _ = fun (_ : t) -> () [@@dead "_"]

  Warning Dead Value
  dce_test.ml 7:1-15
  _ has no side effects and can be removed
  <-- line 7
  let _ = compare [@@dead "_"]
```
These `let _ = compare` bindings are generated in order to silence warnings, but reanalyze warns on them directly.

Perhaps it would make sense to omit warnings on values (and types, and...) whose names start with `_`, as this is what the compiler does. Perhaps with a mode to warn on them anyhow.

[dce_test.tar.gz](https://github.com/cristianoc/reanalyze/files/4493427/dce_test.tar.gz)

**Comment by cristianoc** [comment]
@jberdine is that a ghost location or any other indication that's it's generated code?
Or any other context info one can use to single these cases out?

**Comment by jberdine** [comment]
I don't know of anything other than the leading underscore name. Especially in the case of `deriving_inline`, where the generated code appears in the source just like regular code so that no ppx rewriting needs to be done before compiling.

**Comment by cristianoc** [comment]
Well, there's the `@@deriving_inline` line, plus the fact that it coincides with a type declaration (have to check if the location info coincided exactly).
One possibility is to play with that.
Thought there's the question of what other cases there are.

**Comment by jberdine** [comment]
Yes, for `deriving_inline` I think you could check if the structure or signature item appears between `deriving_inline` and `end` attributes. For plain `deriving` I guess that wouldn't work though. But maybe there is some location-based way to identify those.

I think that there is a higher-level question though: should reanalyze try to interpret the indications that programmers have given by giving things underscore-prefixed names? It is not only generated code that does this. For example, I have some cases where some variable is used only in debug mode, but all uses get compiled out in optimized mode. For those, it can be useful to use an underscore-prefixed name.

Also, it is arguably not great style to use `let _ =` for side-effecting expressions, as `_` can have any type, and `let () =` is safer.

**Comment by cristianoc** [comment]
The `_` is special-cased because some user had issues and wanted to report dead code of that form. So the warning was exactly for that reason.

I guess we're in the ballpark of configuration options. Though I'm leaning toward just turning it off, and keep it in the back pocket if there are requests. And avoid adding a command-line.

Special-casing PPXs seems a complication -- just wanted to dig a big deeper before excluding the possibility.

**Comment by cristianoc** [comment]
For the ppx, is it sufficient to consider `_` or `_foo` in general?

**Comment by jberdine** [comment]
I see. Ok, it sounds like a config thing then, analogous to the difference between `git clean` and `git clean -x`.

**Comment by jberdine** [comment]
The generated code I have seen uses literally `_`. I have seen programmers use `_foo` to tell the compiler to hush while still giving an informative name. My expectation is that if reanalyze warns on `_foo`, people will report it as a false alarm.

**Comment by cristianoc** [comment]
In case of `_foo` the report is only given in case of side effects. So I'll keep on reporting that case. As it's hiding side effects that might not be intentional.
