### ISSUE TITLE
Exception false positive report

### ISSUE THREAD

**Issue by Coobaha** [cristianoc/reanalyze#74]
```
let toMinMax = (str: string) => {
  switch (Js.String.split("-", str)) {
  | [|min, max|] => {min: int_of_string(min), max: int_of_string(max)}
  | _ => {min: (-1), max: (-1)}
  };
};
```

``` 
Exception Analysis
toMinMax might raise Failure and is not annotated with @raises Failure
```

If any pattern is present it should be safe?

**Comment by cristianoc** [comment]
@Coobaha `int_of_string` throws.
```
# int_of_string("");;
Exception: Failure "int_of_string".
```

So its implicit type is 'can raise Failure`.

Function `toMinMax` is not safe as written: it depends on what's passed as `str`.

There are 3 things one can do:
1 Catch `Failure` inside `toMinMax`.
2 Say "I know what I'm doing: it will never called with something dangerous", i.e. annotate the calls to `inf_of_string` with `[@doesNotRaise]`.
3 Say "please caller it's your problem not mine", and annotate it as `[@raises Failure] let toMinMax = (str: string) => {` and let the various callers choose what to do about it.

**Comment by Coobaha** [comment]
Oh indeed, I was thinking that it’s because array destructuring. Thanks for your answer!

**Comment by cristianoc** [comment]
The location range in the text of the warning should tell you where it happens.
